# This file defines the entire Python environment for the application,
# ensuring reproducibility and modularity. [50]

# Use Pyodide as the main interpreter, as the simulator requires packages
# like pandas and plotly that are not available in MicroPython.
interpreter = "pyodide"

# The 'packages' directive here is technically for the main (MicroPython) interpreter,
# but we define the full list needed by the Pyodide worker. This list will be passed
# to the worker upon its creation.
packages = [
  "numpy",
  "pandas",
  "matplotlib",
  "plotly"
]

# The [[fetch]] directive maps local files and directories into Pyodide's
# virtual filesystem, allowing for standard Python imports. [25]
[[fetch]]
from = "./src/"
to_folder = "src"

[[fetch]]
files = ["./data/sample.csv"]
